-- Tables are not sorted because: 
-- Circular dependency between table DEFAULT_SCHEMA.NN_HOST and table DEFAULT_SCHEMA.NN_WORKER: both have foreign keys that reference the other table.
-- Try generating Foreign Keys with ALTER TABLE statements.
CREATE TABLE NN_MESSAGE_TEMPLATE (
       MSG_TEMPLATE_ID BIGINT NOT NULL
     , KEY_VAR_LIST VARCHAR(255) NOT NULL
     , SEQ_VAR_LIST VARCHAR(255) NOT NULL
     , DOMAIN_CD VARCHAR(32) NOT NULL
     , CONSTRAINT PK_NN_MESSAGE_TEMPLATE PRIMARY KEY (MSG_TEMPLATE_ID)
);

CREATE TABLE NN_DOMAIN (
       DOMAIN_CD VARCHAR(32) NOT NULL
     , DOMAIN_PROPERTIES VARCHAR(4000) NOT NULL
     , CONSTRAINT PK_NN_DOMAIN PRIMARY KEY (DOMAIN_CD)
);

CREATE TABLE NN_SCHEDULE (
       SCHEDULE_ID BIGINT NOT NULL
     , JOB_TEMPLATE_ID BIGINT NOT NULL
     , MSG_TEMPLATE_ID BIGINT NOT NULL
     , SEQ_TRANSFORM_RULE VARCHAR(4000) NOT NULL
     , CONSTRAINT PK_NN_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);

CREATE TABLE NN_JOB_TEMPLATE (
       JOB_TEMPLATE_ID BIGINT NOT NULL
     , JOB_NAME VARCHAR(32) NOT NULL
     , END_STAGE VARCHAR(32)
     , MSG_TEMPLATE_ID BIGINT NOT NULL
     , KEY_FILTER_RULE VARCHAR(1024)
     , CONSTRAINT PK_NN_JOB_TEMPLATE PRIMARY KEY (JOB_TEMPLATE_ID)
);

CREATE TABLE NN_STAGE_TEMPLATE (
       STAGE_TEMPLATE_ID BIGINT NOT NULL
     , STAGE_NAME VARCHAR(32)
     , STAGE_DEFINITION VARCHAR(4000)
     , JOB_TEMPLATE_ID BIGINT NOT NULL
     , RAM_COST FLOAT
     , CPU_COST FLOAT
     , CONSTRAINT PK_NN_STAGE_TEMPLATE PRIMARY KEY (STAGE_TEMPLATE_ID)
);

CREATE TABLE NN_STAGE_DEPENDENCY (
       STAGE_TEMPLATE_ID BIGINT NOT NULL
     , DEPEND_ON_STAGE VARCHAR(32) NOT NULL
     , CONSTRAINT PK_NN_STAGE_DEPENDENCY PRIMARY KEY (DEPEND_ON_STAGE, STAGE_TEMPLATE_ID)
);

CREATE TABLE NN_SEQUENCE (
       SEQUENCE_ID BIGINT NOT NULL
     , SCHEDULE_ID BIGINT NOT NULL
     , MSG_ID BIGINT NOT NULL
     , CONSTRAINT PK_NN_SEQUENCE PRIMARY KEY (SEQUENCE_ID)
);

CREATE TABLE NN_MESSAGE (
       MSG_ID BIGINT NOT NULL
     , MSG_STATE VARCHAR(32) NOT NULL
     , KEY_MAP VARCHAR(1024) NOT NULL
     , SEQ_MAP VARCHAR(1024) NOT NULL
     , PREV_MSG_ID BIGINT
     , MSG_TEMPLATE_ID BIGINT NOT NULL
     , CONTEXT_SETTINGS VARCHAR(1024)
     , CONSTRAINT PK_NN_MESSAGE PRIMARY KEY (MSG_ID)
);

CREATE TABLE NN_HOST_GROUP (
       HOST_GROUP_CD VARCHAR(32) NOT NULL
     , CONSTRAINT PK_NN_HOST_GROUP PRIMARY KEY (HOST_GROUP_CD)
);

CREATE TABLE NN_HOST (
       HOST_CD VARCHAR(64) NOT NULL
     , HOST_GROUP_CD VARCHAR(32) NOT NULL
     , HOST_STATUS VARCHAR(32)
     , ACTIVE_WORKER_ID BIGINT
     , CPU_CAPACITY FLOAT NOT NULL
     , RAM_CAPACITY FLOAT NOT NULL
     , CONSTRAINT PK_NN_HOST PRIMARY KEY (HOST_CD)
);

CREATE TABLE NN_WORKER (
       WORKER_ID BIGINT NOT NULL
     , HOST_CD VARCHAR(64) NOT NULL
     , PID VARCHAR(32)
     , WORKER_STATE VARCHAR(32)
     , CONSTRAINT PK_NN_WORKER PRIMARY KEY (WORKER_ID)
);

CREATE TABLE NN_RUN (
       RUN_ID BIGINT NOT NULL
     , STAGE_ID BIGINT
     , WORKER_ID BIGINT NOT NULL
     , PID VARCHAR(32)
     , RUN_STATE VARCHAR(32)
     , CMD VARCHAR(4000)
     , UP_TS TIMESTAMP NOT NULL
     , DOWN_TS TIMESTAMP
     , CONSTRAINT PK_NN_RUN PRIMARY KEY (RUN_ID)
);

CREATE TABLE NN_RUN_ARTIFACT (
       RUN_ID BIGINT NOT NULL
     , ARTIFACT_NAME VARCHAR(32) NOT NULL
     , TS TIMESTAMP NOT NULL
     , ARTIFACT_DATA VARCHAR(1024)
     , CONSTRAINT PK_NN_RUN_ARTIFACT PRIMARY KEY (TS, ARTIFACT_NAME, RUN_ID)
);

CREATE TABLE NN_STAGE (
       STAGE_ID BIGINT NOT NULL
     , JOB_ID BIGINT NOT NULL
     , STAGE_TEMPLATE_ID BIGINT NOT NULL
     , STAGE_STATE VARCHAR(32)
     , RETRIES_LEFT BIGINT
     , CONSTRAINT PK_NN_STAGE PRIMARY KEY (STAGE_ID)
);

CREATE TABLE NN_JOB (
       JOB_ID BIGINT NOT NULL
     , MSG_ID BIGINT NOT NULL
     , JOB_TEMPLATE_ID BIGINT NOT NULL
     , TS TIMESTAMP
     , JOB_STATE VARCHAR(32)
     , CONSTRAINT PK_NN_JOB PRIMARY KEY (JOB_ID)
);

CREATE TABLE NN_USER (
       USER_CD VARCHAR(32) NOT NULL
     , AUTH_TOKEN VARCHAR(128)
     , USER_SETTINGS VARCHAR(1024)
     , CONSTRAINT PK_NN_USER PRIMARY KEY (USER_CD)
);

ALTER TABLE NN_MESSAGE_TEMPLATE
  ADD CONSTRAINT FK_NN_MESSAGE_TEMPLATE_2
      FOREIGN KEY (DOMAIN_CD)
      REFERENCES NN_DOMAIN (DOMAIN_CD);

ALTER TABLE NN_SCHEDULE
  ADD CONSTRAINT FK_NN_SCHEDULE_1
      FOREIGN KEY (JOB_TEMPLATE_ID)
      REFERENCES NN_JOB_TEMPLATE (JOB_TEMPLATE_ID);

ALTER TABLE NN_SCHEDULE
  ADD CONSTRAINT FK_NN_SCHEDULE_2
      FOREIGN KEY (MSG_TEMPLATE_ID)
      REFERENCES NN_MESSAGE_TEMPLATE (MSG_TEMPLATE_ID);

ALTER TABLE NN_JOB_TEMPLATE
  ADD CONSTRAINT FK_NN_JOB_TEMPLATE_1
      FOREIGN KEY (MSG_TEMPLATE_ID)
      REFERENCES NN_MESSAGE_TEMPLATE (MSG_TEMPLATE_ID);

ALTER TABLE NN_STAGE_TEMPLATE
  ADD CONSTRAINT FK_NN_STAGE_TEMPLATE_1
      FOREIGN KEY (JOB_TEMPLATE_ID)
      REFERENCES NN_JOB_TEMPLATE (JOB_TEMPLATE_ID);

ALTER TABLE NN_STAGE_DEPENDENCY
  ADD CONSTRAINT FK_NN_STAGE_DEPENDENCY_1
      FOREIGN KEY (STAGE_TEMPLATE_ID)
      REFERENCES NN_STAGE_TEMPLATE (STAGE_TEMPLATE_ID);

ALTER TABLE NN_SEQUENCE
  ADD CONSTRAINT FK_NN_SEQUENCE_1
      FOREIGN KEY (SCHEDULE_ID)
      REFERENCES NN_SCHEDULE (SCHEDULE_ID);

ALTER TABLE NN_SEQUENCE
  ADD CONSTRAINT FK_NN_SEQUENCE_2
      FOREIGN KEY (MSG_ID)
      REFERENCES NN_MESSAGE (MSG_ID);

ALTER TABLE NN_MESSAGE
  ADD CONSTRAINT FK_NN_MESSAGE_1
      FOREIGN KEY (PREV_MSG_ID)
      REFERENCES NN_MESSAGE (MSG_ID);

ALTER TABLE NN_MESSAGE
  ADD CONSTRAINT FK_NN_MESSAGE_4
      FOREIGN KEY (MSG_TEMPLATE_ID)
      REFERENCES NN_MESSAGE_TEMPLATE (MSG_TEMPLATE_ID);

ALTER TABLE NN_HOST
  ADD CONSTRAINT FK_NN_HOST_1
      FOREIGN KEY (HOST_GROUP_CD)
      REFERENCES NN_HOST_GROUP (HOST_GROUP_CD);

ALTER TABLE NN_HOST
  ADD CONSTRAINT FK_NN_HOST_2
      FOREIGN KEY (ACTIVE_WORKER_ID)
      REFERENCES NN_WORKER (WORKER_ID);

ALTER TABLE NN_WORKER
  ADD CONSTRAINT FK_NN_WORKER_1
      FOREIGN KEY (HOST_CD)
      REFERENCES NN_HOST (HOST_CD);

ALTER TABLE NN_RUN
  ADD CONSTRAINT FK_NN_RUN_1
      FOREIGN KEY (STAGE_ID)
      REFERENCES NN_STAGE (STAGE_ID);

ALTER TABLE NN_RUN
  ADD CONSTRAINT FK_NN_RUN_2
      FOREIGN KEY (WORKER_ID)
      REFERENCES NN_WORKER (WORKER_ID);

ALTER TABLE NN_RUN_ARTIFACT
  ADD CONSTRAINT FK_NN_RUN_ARTIFACT_1
      FOREIGN KEY (RUN_ID)
      REFERENCES NN_RUN (RUN_ID);

ALTER TABLE NN_STAGE
  ADD CONSTRAINT FK_NN_STAGE_1
      FOREIGN KEY (JOB_ID)
      REFERENCES NN_JOB (JOB_ID);

ALTER TABLE NN_STAGE
  ADD CONSTRAINT FK_NN_STAGE_2
      FOREIGN KEY (STAGE_TEMPLATE_ID)
      REFERENCES NN_STAGE_TEMPLATE (STAGE_TEMPLATE_ID);

ALTER TABLE NN_JOB
  ADD CONSTRAINT FK_NN_JOB_1
      FOREIGN KEY (MSG_ID)
      REFERENCES NN_MESSAGE (MSG_ID);

ALTER TABLE NN_JOB
  ADD CONSTRAINT FK_NN_JOB_2
      FOREIGN KEY (JOB_TEMPLATE_ID)
      REFERENCES NN_JOB_TEMPLATE (JOB_TEMPLATE_ID);

