-- Tables are not sorted because: 
-- Circular reference between DEFAULT_SCHEMA.NN_HOST and DEFAULT_SCHEMA.NN_WORKER
-- Try generating Foreign Keys with ALTER TABLE statements.
CREATE TABLE NN_DOMAIN (
       DOMAIN_CD VARCHAR(32) NOT NULL
     , DOMAIN_STATE VARCHAR(32) NOT NULL
     , PROPERTIES_ID BIGINT NOT NULL
     , MSGCONFIG_ID BIGINT NOT NULL
     , UPDATED_TS TIMESTAMP
     , CONSTRAINT PK_NN_DOMAIN PRIMARY KEY (DOMAIN_CD)
);

CREATE TABLE NN_MESSAGE (
       MSG_ID BIGINT NOT NULL
     , MSG_NAME VARCHAR(32) NOT NULL
     , MSG_STATE VARCHAR(32) NOT NULL
     , MSG_PARAMETERS VARCHAR(4000) NOT NULL
     , MSG_TEMPLATE_ID BIGINT NOT NULL
     , CONTEXT_SETTINGS VARCHAR(4000)
     , USER_CD VARCHAR(32) NOT NULL
     , DOMAIN_CD VARCHAR(32) NOT NULL
     , CONSTRAINT PK_NN_MESSAGE PRIMARY KEY (MSG_ID)
);

CREATE TABLE NN_HOST_GROUP (
       HOST_GROUP_CD VARCHAR(32) NOT NULL
     , CONSTRAINT PK_NN_HOST_GROUP PRIMARY KEY (HOST_GROUP_CD)
);

CREATE TABLE NN_HOST (
       HOST_CD VARCHAR(64) NOT NULL
     , HOST_GROUP_CD VARCHAR(32) NOT NULL
     , HOST_STATUS VARCHAR(32)
     , ACTIVE_WORKER_ID BIGINT
     , CONSTRAINT PK_NN_HOST PRIMARY KEY (HOST_CD)
);

CREATE TABLE NN_WORKER (
       WORKER_ID BIGINT NOT NULL
     , HOST_CD VARCHAR(64) NOT NULL
     , PID VARCHAR(32)
     , WORKER_STATE VARCHAR(32)
     , CONSTRAINT PK_NN_WORKER PRIMARY KEY (WORKER_ID)
);

CREATE TABLE NN_RUN (
       RUN_ID BIGINT NOT NULL
     , STAGE_ID BIGINT
     , WORKER_ID BIGINT NOT NULL
     , PID VARCHAR(32)
     , RUN_STATE VARCHAR(32)
     , CMD VARCHAR(4000)
     , UP_TS TIMESTAMP NOT NULL
     , DOWN_TS TIMESTAMP
     , CONSTRAINT PK_NN_RUN PRIMARY KEY (RUN_ID)
);

CREATE TABLE NN_RUN_ARTIFACT (
       RUN_ID BIGINT NOT NULL
     , ARTIFACT_NAME VARCHAR(32) NOT NULL
     , TS TIMESTAMP NOT NULL
     , ARTIFACT_DATA VARCHAR(1024)
     , CONSTRAINT PK_NN_RUN_ARTIFACT PRIMARY KEY (TS, ARTIFACT_NAME, RUN_ID)
);

CREATE TABLE NN_STAGE (
       STAGE_ID BIGINT NOT NULL
     , JOB_ID BIGINT NOT NULL
     , STAGE_STATE VARCHAR(32)
     , RETRIES_LEFT BIGINT
     , STAGE_NAME VARCHAR(32)
     , CONSTRAINT PK_NN_STAGE PRIMARY KEY (STAGE_ID)
);

CREATE TABLE NN_JOB (
       JOB_ID BIGINT NOT NULL
     , MSG_ID BIGINT NOT NULL
     , TS TIMESTAMP
     , JOB_STATE VARCHAR(32)
     , RESPONSIBLE CHAR(1) NOT NULL
     , JOB_NAME VARCHAR(32) NOT NULL
     , CONSTRAINT PK_NN_JOB PRIMARY KEY (JOB_ID)
);

CREATE TABLE NN_USER (
       USER_CD VARCHAR(32) NOT NULL
     , AUTH_TOKEN VARCHAR(128)
     , USER_SETTINGS VARCHAR(1024)
     , SYSTEM_USER CHAR(1)
     , CONSTRAINT PK_NN_USER PRIMARY KEY (USER_CD)
);

CREATE TABLE NN_CONFIGURATION (
       CONFIG_ID BIGINT NOT NULL
     , CONFIG_NAME VARCHAR(32) NOT NULL
     , CONFIG_DATA CLOB(64 K)
     , CREATED_TS TIMESTAMP
     , CONSTRAINT PK_NN_CONFIGURATION PRIMARY KEY (CONFIG_ID)
);

CREATE TABLE NN_ID_FACTORY (
       TABLE_NAME VARCHAR(64) NOT NULL
     , COUNTER BIGINT
     , CONSTRAINT PK_NN_ID_FACTORY PRIMARY KEY (TABLE_NAME)
);

ALTER TABLE NN_DOMAIN
  ADD CONSTRAINT FK_NN_DOMAIN_1
      FOREIGN KEY (PROPERTIES_ID)
      REFERENCES NN_CONFIGURATION (CONFIG_ID);

ALTER TABLE NN_DOMAIN
  ADD CONSTRAINT FK_NN_DOMAIN_2
      FOREIGN KEY (MSGCONFIG_ID)
      REFERENCES NN_CONFIGURATION (CONFIG_ID);

ALTER TABLE NN_MESSAGE
  ADD CONSTRAINT FK_NN_MESSAGE_3
      FOREIGN KEY (USER_CD)
      REFERENCES NN_USER (USER_CD);

ALTER TABLE NN_MESSAGE
  ADD CONSTRAINT FK_NN_MESSAGE_5
      FOREIGN KEY (DOMAIN_CD)
      REFERENCES NN_DOMAIN (DOMAIN_CD);

ALTER TABLE NN_HOST
  ADD CONSTRAINT FK_NN_HOST_1
      FOREIGN KEY (HOST_GROUP_CD)
      REFERENCES NN_HOST_GROUP (HOST_GROUP_CD);

ALTER TABLE NN_HOST
  ADD CONSTRAINT FK_NN_HOST_2
      FOREIGN KEY (ACTIVE_WORKER_ID)
      REFERENCES NN_WORKER (WORKER_ID);

ALTER TABLE NN_WORKER
  ADD CONSTRAINT FK_NN_WORKER_1
      FOREIGN KEY (HOST_CD)
      REFERENCES NN_HOST (HOST_CD);

ALTER TABLE NN_RUN
  ADD CONSTRAINT FK_NN_RUN_1
      FOREIGN KEY (STAGE_ID)
      REFERENCES NN_STAGE (STAGE_ID);

ALTER TABLE NN_RUN
  ADD CONSTRAINT FK_NN_RUN_2
      FOREIGN KEY (WORKER_ID)
      REFERENCES NN_WORKER (WORKER_ID);

ALTER TABLE NN_RUN_ARTIFACT
  ADD CONSTRAINT FK_NN_RUN_ARTIFACT_1
      FOREIGN KEY (RUN_ID)
      REFERENCES NN_RUN (RUN_ID);

ALTER TABLE NN_STAGE
  ADD CONSTRAINT FK_NN_STAGE_1
      FOREIGN KEY (JOB_ID)
      REFERENCES NN_JOB (JOB_ID);

ALTER TABLE NN_JOB
  ADD CONSTRAINT FK_NN_JOB_1
      FOREIGN KEY (MSG_ID)
      REFERENCES NN_MESSAGE (MSG_ID);

